name: ezytdl distributable build
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Release Name"
        required: false
        default: 'Stable Release'

jobs:
  release_info:
    runs-on: ubuntu-latest
    name: Create release tag

    permissions: write-all

    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get release metadata
        id: get_release_metadata
        run: |
          echo "TAG_NAME=$(node -e "console.log(require('./package.json').version)")" >> "$GITHUB_ENV"
          echo "RELEASE_TITLE=${{ inputs.name }}" >> "$GITHUB_ENV"
          echo "RELEASE_NAME=v$(node -e "console.log(require('./package.json').version)") - ${{ inputs.name }}" >> "$GITHUB_ENV"
          echo "BODY_PATH=$(echo "$(pwd)/release-notes.md")" >> "$GITHUB_ENV"

      - name: Create release notes
        id: create_notes
        run: |
          node devscripts/generateReleaseNotes.js stable

      - name: Create release draft
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          commit: ${{ github.sha }}
          draft: true
          prerelease: false
          makeLatest: true
          bodyFile: ${{ env.BODY_PATH }}
          omitBody: false
          omitBodyDuringUpdate: true
  
  linux-dist:
    runs-on: ubuntu-22.04

    needs: release_info

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: '18'

      - name: Install npm deps
        run: |
          npm install

      # install flatpak and flatpak-builder
      - name: Install flatpak and sdk
        run: |
          sudo apt-get install flatpak flatpak-builder -y
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install --user --no-deps --arch x86_64 --assumeyes runtime/org.freedesktop.Sdk/x86_64/23.08
          flatpak install --user --no-deps --arch x86_64 --assumeyes runtime/org.freedesktop.Platform/x86_64/23.08

      - name: Build app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run dist
  macos-dist:
    runs-on: macos-latest

    needs: release_info

    permissions: write-all

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: '18'

      - name: Install npm deps
        run: |
          npm install

      - name: Build app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run dist
  windows-dist:
    runs-on: windows-latest

    needs: release_info

    permissions: write-all

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node.js & NPM
        uses: actions/setup-node@main
        with:
          node-version: '18'

      - name: Install npm deps
        run: |
          npm install

      - name: Build app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run dist